#configuration
## DEF: Dal modulo network importa solo la funzione LoRa
from network import LoRa

#application-level device identifier
## Si assegna alla variabile DEVICE_ID un valore intero
DEVICE_ID = 1

# authentication credentials (specific for each device, generated by LoRa backend)
## DEF: Si assegna alla variabile LORA_CRED_ABP tre valori, creando un TUPLE. I tuple sono come delle liste con la sola differenza che il contenuo non può essere 
## modificato. Questa tupla contiene tre stringhe che sono i parametri di autenticazione ABP
LORA_CRED_ABP = ('010b0932', '53b57fc6767581cecc9b69f040e1c34d', 'f643c9f49b6689566a7ff167bb5f2fb0')


# initialized (hard-coded) sampling/sending interval (will be modified and adapted by the synchronization mechanism)
INTERVAL_PRE = 120000 # (milliseconds)

# led activation (for testing only)
##DEF: Si assegna alla variabile LED_ON il valore Booleano di True
LED_ON = True
### It is suggested to not modify the following configurations

# authentication method
# ABP (Authentication By Personalization) suggested.
# ABP = False  enables OTA (Over The Air authentication)
ABP = True
# For OTA specific OTA-credentials must be used
# LORA_CRED_OTA = ('240ac4fffec74d2c', '0000000000000000', '4bb13766c2c737c1b77096d72b473fb2')

# LoRa payload format
# (2 Bytes for device ID, 8 float numbers: temp humid ph1 ph2 ph3 volt1 volt2 volt3)
## DEF: Si definisce la variabile LORA_PKG_FORMAT con una stringa, in cui: i byte !H saranno assegnati al Device ID e le restanti otto f ai
## parametri di: temp humid ph1 ph2 ph3 volt1 volt2 volt3
LORA_PKG_FORMAT = "!Hffffffff"

# waiting time (for receive windows to expire)
WAITING_SLEEP = 8 #seconds

# LoRa PHY settings
LORA_FREQUENCY = 868100000
LORA_NODE_DR = 5 # LoRa datarate DR=0 sets SF = 12, DR=5 sets SF = 7 (DR=0 suggested for maximum range)

## DEF: per le variabili LORA_DEVICE_CLASS e LORA_REGION sono definiti dei valori presi sempre dal modulo network, rispettivamente valgono
## LORA_DEVICE_CLASS = LoRa.CLASS_C = 2 e LORA_REGION = LoRa.EU868 = 5
LORA_DEVICE_CLASS = LoRa.CLASS_C
LORA_REGION = LoRa.EU868 # LORAWAN region (Europe)
# alternatives:
# Asia = LoRa.AS923
# Australia = LoRa.AU915
# United States = LoRa.US915
